# Generated by Django 4.1.1 on 2023-03-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_image', models.FileField(default=None, max_length=250, upload_to='service')),
                ('serv_name', models.CharField(max_length=50)),
                ('serv_desc', models.TextField(max_length=500)),
                ('serv_status', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('serv_Trending', models.BooleanField(default=False, help_text='0=default,1=Trending')),
                ('serv_meta_title', models.CharField(max_length=50)),
                ('serv_meta_keyword', models.CharField(default=None, max_length=50)),
                ('serv_meta_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(default=None, max_length=250, null=True, upload_to='service')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.TextField(default=None, max_length=500)),
                ('product_status', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('product_Trending', models.BooleanField(default=False, help_text='0=default,1=Trending')),
                ('product_meta_title', models.CharField(max_length=50)),
                ('product_meta_keyword', models.CharField(max_length=50)),
                ('product_meta_description', models.CharField(max_length=50)),
                ('product_small_description', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField()),
                ('product_original_price', models.FloatField()),
                ('product_Selling_price', models.FloatField()),
                ('product_tag', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.services')),
            ],
        ),
    ]
